"""Do Machines Dream of Departure? simulator package."""

from .adofai_chart import (
    AdoFaiAction,
    AdoFaiChart,
    load_adofai,
    parse_adofai_bytes,
    parse_adofai_text,
)
from .adofai_geometry import AdoFaiFloorGeometry, build_floor_geometry
from .adofai_playable import (
    PlayableChartSegment,
    PlayableChartTarget,
    build_playable_segment,
)
from .adofai_rules import (
    ABSOLUTE_MIN_S,
    COUNTED_BASE_DEG,
    EARLY_LATE_PERFECT_BASE_DEG,
    EARLY_LATE_PERFECT_MIN_S,
    LENIENT_COUNTED_MIN_S,
    LENIENT_OPTION_MINIMUM_BPM_CUSTOM,
    MOBILE_COUNTED_MIN_S,
    MOBILE_EARLY_LATE_PERFECT_MIN_S,
    MOBILE_PERFECT_MIN_S,
    MULTIPRESS_DAMAGE,
    MULTIPRESS_RECOVERY_PER_BEAT,
    MULTIPRESS_RESET_AFTER_BEATS,
    NORMAL_COUNTED_MIN_S,
    NORMAL_THRESHOLD_BPM,
    OVERLOAD_DAMAGE,
    OVERLOAD_LIMIT,
    OVERLOAD_RECOVERY_PER_BEAT,
    PERFECT_BASE_DEG,
    PURE_PERFECT_MIN_S,
    STRICT_COUNTED_MIN_S,
    STRICT_OPTION_MINIMUM_BPM_CUSTOM,
    OverloadCounter,
    TimingDifficulty,
    TimingJudgement,
    TimingWindows,
    classify_normal_timing,
    classify_timing,
    normal_accuracy_percent,
    normal_timing_windows,
    timing_windows,
    x_accuracy_components,
    x_accuracy_percent,
    x_accuracy_weight,
)
from .adofai_timing import (
    AdoFaiFloorTiming,
    CompiledAdoFaiChart,
    CompiledChartFloor,
    VisibleChartFloor,
    build_stock_timing,
    compile_adofai,
    load_compiled_adofai,
)
from .body import (
    BilateralConfig,
    BilateralState,
    BodyConfig,
    FingerConfig,
    FingerState,
    HandConfig,
    HandState,
    TwoFingerBody,
)
from .calibration import INITIAL_RATE_TARGETS, RateTarget
from .evaluator import EvaluationSummary, Judgement, TargetHit, TimingEvaluator
from .keyboard import KeyConfig, KeyEvent, KeyState, TwoKeyKeyboard
from .motor_env import (
    LeftThresholdReflexPolicy,
    MotorAction,
    MotorDiagnostics,
    MotorEnv,
    MotorObservation,
    MotorPolicy,
    MotorTransition,
    TimedKeyEvent,
)
from .pattern_geometry_env import (
    PatternGeometryObservation,
    PatternGeometryStep,
    PatternMemoryGeometryEnv,
)
from .pattern_memory import PatternMemory, PatternMemoryEntry, PatternMemoryFeatures
from .perception import VisualCueConfig, VisualCueEncoder, VisualCueObservation
from .planet_perception import (
    PlanetGeometryObservation,
    PlanetVisionConfig,
    StraightPlanetGeometryEncoder,
)
from .profiles import PERSONAL_BLUE_SWITCH_V0_1_NAME, personal_blue_switch_v0_1
from .real_chart_env import (
    RealChartMotorEnv,
    RealChartObservation,
    RealChartStep,
    RelativeVisibleFloor,
)
from .real_chart_features import (
    DEFAULT_REAL_CHART_FEATURE_CONFIG,
    REAL_CHART_EVENT_MARKERS,
    REAL_CHART_FLOOR_FEATURE_DIM,
    REAL_CHART_INPUT_DIM,
    RealChartFeatureConfig,
    encode_real_chart_observation,
)
from .rhythm_env import (
    EpisodeStats,
    RewardConfig,
    RhythmMotorEnv,
    RhythmObservation,
    RhythmStep,
    make_regular_targets,
)
from .simulator import Simulation, SimulationConfig, StepResult

__all__ = [
    "AdoFaiAction",
    "AdoFaiChart",
    "AdoFaiFloorGeometry",
    "AdoFaiFloorTiming",
    "CompiledAdoFaiChart",
    "CompiledChartFloor",
    "VisibleChartFloor",
    "PlayableChartSegment",
    "PlayableChartTarget",
    "build_playable_segment",
    "load_adofai",
    "parse_adofai_bytes",
    "parse_adofai_text",
    "build_floor_geometry",
    "build_stock_timing",
    "compile_adofai",
    "load_compiled_adofai",
    "ABSOLUTE_MIN_S",
    "COUNTED_BASE_DEG",
    "EARLY_LATE_PERFECT_BASE_DEG",
    "EARLY_LATE_PERFECT_MIN_S",
    "LENIENT_COUNTED_MIN_S",
    "LENIENT_OPTION_MINIMUM_BPM_CUSTOM",
    "MOBILE_COUNTED_MIN_S",
    "MOBILE_EARLY_LATE_PERFECT_MIN_S",
    "MOBILE_PERFECT_MIN_S",
    "MULTIPRESS_DAMAGE",
    "MULTIPRESS_RECOVERY_PER_BEAT",
    "MULTIPRESS_RESET_AFTER_BEATS",
    "NORMAL_COUNTED_MIN_S",
    "NORMAL_THRESHOLD_BPM",
    "OVERLOAD_DAMAGE",
    "OVERLOAD_LIMIT",
    "OVERLOAD_RECOVERY_PER_BEAT",
    "PERFECT_BASE_DEG",
    "PURE_PERFECT_MIN_S",
    "STRICT_COUNTED_MIN_S",
    "STRICT_OPTION_MINIMUM_BPM_CUSTOM",
    "OverloadCounter",
    "TimingDifficulty",
    "TimingJudgement",
    "TimingWindows",
    "classify_normal_timing",
    "classify_timing",
    "normal_accuracy_percent",
    "normal_timing_windows",
    "timing_windows",
    "x_accuracy_components",
    "x_accuracy_percent",
    "x_accuracy_weight",
    "BilateralConfig",
    "BilateralState",
    "BodyConfig",
    "FingerConfig",
    "FingerState",
    "HandConfig",
    "HandState",
    "TwoFingerBody",
    "RateTarget",
    "INITIAL_RATE_TARGETS",
    "EvaluationSummary",
    "Judgement",
    "TargetHit",
    "TimingEvaluator",
    "PERSONAL_BLUE_SWITCH_V0_1_NAME",
    "personal_blue_switch_v0_1",
    "KeyConfig",
    "KeyEvent",
    "KeyState",
    "TwoKeyKeyboard",
    "MotorAction",
    "MotorObservation",
    "TimedKeyEvent",
    "MotorDiagnostics",
    "MotorTransition",
    "MotorPolicy",
    "MotorEnv",
    "LeftThresholdReflexPolicy",
    "PatternMemory",
    "PatternMemoryEntry",
    "PatternMemoryFeatures",
    "PatternMemoryGeometryEnv",
    "PatternGeometryObservation",
    "PatternGeometryStep",
    "VisualCueConfig",
    "VisualCueEncoder",
    "VisualCueObservation",
    "PlanetGeometryObservation",
    "PlanetVisionConfig",
    "StraightPlanetGeometryEncoder",
    "RelativeVisibleFloor",
    "RealChartObservation",
    "RealChartStep",
    "RealChartMotorEnv",
    "RealChartFeatureConfig",
    "DEFAULT_REAL_CHART_FEATURE_CONFIG",
    "REAL_CHART_EVENT_MARKERS",
    "REAL_CHART_FLOOR_FEATURE_DIM",
    "REAL_CHART_INPUT_DIM",
    "encode_real_chart_observation",
    "EpisodeStats",
    "RewardConfig",
    "RhythmMotorEnv",
    "RhythmObservation",
    "RhythmStep",
    "make_regular_targets",
    "Simulation",
    "SimulationConfig",
    "StepResult",
]
